In [15]:
# paramètres : je les ai réunis ici afin d'avoir un code 'modulaire' : on peut choisir ce qu'on veut
# observer en fonction de paramètres listés ici

# pour le choix du matériau
cle_materiau = "mp-20072"

# propre à l'utilisateur
cle_utilisateur = "om6hvHlirPcyuxXF"

# le nombre de décimales qu'on veut voir pour les valeurs chiffrées
dec = 4

In [16]:
# téléchargement

from pymatgen.symmetry import analyzer as az
from pymatgen.ext.matproj import MPRester
from numpy import around

with MPRester(cle_utilisateur) as m:
    structure = m.get_structure_by_material_id(cle_materiau)

In [17]:
# on recupere les vecteurs de base, décrits via leurs angles et longueurs, pour la maille réciproque et la maille directe

# la structure qu'on va utiliser est une cellule primitive définie selon les principes de Setyawan, W., & Curtarolo, S. (2010)
# (information trouvée dans la documentation pymatgen)
structure = az.SpacegroupAnalyzer(structure).get_primitive_standard_structure()

maille = structure.lattice
maille_reciproque = maille.reciprocal_lattice

# on imprime les résultats
print('vecteurs du reseau de base :')
print(str(around(maille.abc,dec))+' [ångström] ')
print('angles :')
print(str(around(maille.angles,dec))+' [ångström] ')
print('\nvecteurs du reseau reciproque :')
print(str(around(maille_reciproque.angles,dec))+' [ångström] ')
print('angles :')
print(str(around(maille_reciproque.angles,dec))+' [ångström] ')

vecteurs du reseau de base :
[6.0945 6.0945 6.0945] [ångström] 
angles :
[36.9035 36.9035 36.9035] [ångström] 

vecteurs du reseau reciproque :
[116.3808 116.3808 116.3808] [ångström] 
angles :
[116.3808 116.3808 116.3808] [ångström] 


Nous pouvons dès lors remarquer que $a = b = c$ et $\alpha = \beta = \gamma$.

In [18]:
# on recupere le systeme crystallin, le groupe ponctuel et le type de maille

an = az.SpacegroupAnalyzer(structure)

print('systeme crystallin :')
print(an.get_crystal_system())
print('\ngroupe ponctuel :')
print(an.get_point_group_symbol())
print('\ntype de maille :')
print(an.get_lattice_type())

systeme crystallin :
trigonal

groupe ponctuel :
-3m

type de maille :
rhombohedral


Comme on pouvait s'y attendre vu que $a = b = c$ et $\alpha = \beta = \gamma$, on a un systeme cristallin trigonal, avec maille rhombohédrique.