In [2]:
# téléchargement

from pymatgen.symmetry import analyzer as az
from pymatgen.ext.matproj import MPRester
from numpy import dot
from numpy import around

cle_materiau = "mp-20072"
cle_utilisateur = "om6hvHlirPcyuxXF"

with MPRester(cle_utilisateur) as m:
    structure = m.get_structure_by_material_id(cle_materiau)

In [17]:
an = az.SpacegroupAnalyzer(structure)

# on récupère les informations de site sur 3 atomes différents
sites = an.get_primitive_standard_structure().sites[0:3]

# on prend 3 opérations de symétries différentes de l'identité et qui ne sont pas l'opposé d'une opération déjà utilisée
symetries = an.get_symmetry_operations()[2:8:2]

# on fait un bel affichage
i = 0
for s in symetries :
    i+=1
    rot_matrix = s.rotation_matrix
    print('\n\nsymétrie '+str(i)+':')
    print('matrice de rotation :')
    print(rot_matrix)
    print('\nvecteur de translation : '+str(s.translation_vector)+'\n')
    for site in sites :
        print('nouvelle position pour l\'atome "'+str(site.specie)+'" : '+str(around(dot(site.coords, rot_matrix),4)))



symétrie 1:
matrice de rotation :
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

vecteur de translation : [0. 0. 0.]

nouvelle position pour l'atome "La" : [ 1.6392  8.35   -0.    ]
nouvelle position pour l'atome "Cu" : [0. 0. 0.]
nouvelle position pour l'atome "O" : [ 0.3497  1.7815 -0.    ]


symétrie 2:
matrice de rotation :
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]

vecteur de translation : [0. 0. 0.]

nouvelle position pour l'atome "La" : [-0.      1.6392  8.35  ]
nouvelle position pour l'atome "Cu" : [0. 0. 0.]
nouvelle position pour l'atome "O" : [-0.      0.3497  1.7815]


symétrie 3:
matrice de rotation :
[[ 0.  0. -1.]
 [ 0. -1.  0.]
 [-1.  0.  0.]]

vecteur de translation : [0. 0. 0.]

nouvelle position pour l'atome "La" : [-1.6392  0.     -8.35  ]
nouvelle position pour l'atome "Cu" : [0. 0. 0.]
nouvelle position pour l'atome "O" : [-0.3497  0.     -1.7815]
