In [110]:
# téléchargement

from pymatgen.symmetry import analyzer as az
from pymatgen.ext.matproj import MPRester
import numpy as np

cle_materiau = "mp-20072"
cle_utilisateur = "om6hvHlirPcyuxXF"

with MPRester(cle_utilisateur) as m:
    structure = m.get_structure_by_material_id(cle_materiau)

In [117]:
# petite fonction utilitaire avec exemple

def give_coord(A):
    """
    détermine les nouvelles coordonnées d'un point (x,y,z)
    en fonction de la matrice de rotation A:
    
    A_ij appartient a {1,0,-1}
    
                    1 0 0
    résultat si A = 0 1 0  : ['x','y','z']
                    0 0 1
    """
    x = ['x','y','z']
    y = ['']*3
    index = [0,1,2] 
    for i in index:
        for j in index:
            if A[i][j] == 1:
                if y[j] == '':
                    y[j] = x[i]
                else :
                    y[j] += '+'+x[i]
                
            if A[i][j] == -1:
                y[j] += '-'+ x[i]
    return y

A = np.zeros((3,3))
A[0][1] = -1
A[1][0] = -1
A[2][2] = 1
print(A,end='\n\n')
print(give_coord(A))

[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]

['-y', '-x', 'z']


In [119]:
an = az.SpacegroupAnalyzer(structure)
structure = an.get_conventional_standard_structure()
an = az.SpacegroupAnalyzer(structure)


# on récupère les informations de site sur 3 atomes différents
sites = an.get_primitive_standard_structure().sites[0:3]
for site in sites:
    print('position de l\'atome "'+str(site.specie)+'" : '+str(np.around(site.coords,4)))

# on prend 3 opérations de symétries différentes de l'identité et qui ne sont pas l'opposé d'une opération déjà utilisée
all_symetries = an.get_symmetry_operations()
symetries = [all_symetries[7], all_symetries[12], all_symetries[25]]

# on fait un bel affichage
i = 0
for s in symetries :
    i+=1 
    rot_matrix = s.rotation_matrix
    tr_vector = s.translation_vector
    
    print('\n\nsymétrie '+str(i)+':')
    print('matrice de rotation :')
    print(np.around(rot_matrix),end='\n\n')
    print(give_coord(rot_matrix))
    print('\nvecteur de translation : '+str(np.around(tr_vector,2))+'\n')
    
    for site in sites :
        new_coord = np.dot(site.coords, rot_matrix)+tr_vector
        print('nouvelle position pour l\'atome "'+str(site.specie)+'" : '+str(np.around(new_coord,4)))

position de l'atome "La" : [ 8.35   -0.      1.6392]
position de l'atome "Cu" : [0. 0. 0.]
position de l'atome "O" : [14.9184 -0.      2.9287]


symétrie 1:
matrice de rotation :
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]

['-y', '-x', 'z']

vecteur de translation : [0. 0. 0.]

nouvelle position pour l'atome "La" : [ 0.     -8.35    1.6392]
nouvelle position pour l'atome "Cu" : [0. 0. 0.]
nouvelle position pour l'atome "O" : [  0.     -14.9184   2.9287]


symétrie 2:
matrice de rotation :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

['x', 'y', 'z']

vecteur de translation : [0.67 0.33 0.33]

nouvelle position pour l'atome "La" : [9.0166 0.3333 1.9726]
nouvelle position pour l'atome "Cu" : [0.6667 0.3333 0.3333]
nouvelle position pour l'atome "O" : [15.585   0.3333  3.262 ]


symétrie 3:
matrice de rotation :
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]

['-x', '-y', '-z']

vecteur de translation : [0.33 0.67 0.67]

nouvelle position pour l'atome "La" : [-8.0166  0.6667 -0.9726]
nouvelle p